<#
.SYNOPSIS
    Generates the table-based index.html from per-repo meta.json files.
.DESCRIPTION
    Scans docs/*/meta.json to discover all repos and their reports,
    then generates a table with repos as columns and report types as rows.
    Includes client-side JS for live "Xh ago" relative timestamps.
.PARAMETER DocsDir
    Root docs directory (default: docs/).
#>
[CmdletBinding()]
param(
    [string]$DocsDir = "docs"
)

$ErrorActionPreference = "Stop"

# Discover all repo metadata
$metaFiles = Get-ChildItem -Path $DocsDir -Filter "meta.json" -Recurse
$repos = @()
foreach ($mf in $metaFiles) {
    $raw = Get-Content $mf.FullName -Raw
    $meta = $raw | ConvertFrom-Json
    # Preserve ISO timestamp as string (ConvertFrom-Json may parse it as DateTime)
    if ($meta.updated -is [datetime]) {
        $meta.updated = $meta.updated.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    }
    $repos += $meta
}

if ($repos.Count -eq 0) {
    Write-Warning "No meta.json files found in $DocsDir"
    return
}

# Sort repos: runtime first, then alphabetical
$repos = @($repos | Sort-Object { if ($_.slug -eq "runtime") { "0" } else { $_.slug } })

# All known report types in display order
$reportTypes = @(
    @{ Id = "top15"; Title = "Top 25 Actionable" }
    @{ Id = "community"; Title = "Community Awaiting Review" }
    @{ Id = "quick-wins"; Title = "Quick Wins: Ready to Merge" }
)

# Build header row — link to the pulls page, not the repo homepage
$headerCells = $repos | ForEach-Object {
    $repoShort = $_.slug
    "<th><a href=`"https://github.com/$($_.repo)/pulls`">$repoShort</a></th>"
}
$headerRow = "<tr><th>Report</th>$($headerCells -join '')</tr>"

# Build data rows
$dataRows = foreach ($rt in $reportTypes) {
    $cells = foreach ($repo in $repos) {
        $reportInfo = $null
        if ($repo.reports -and $repo.reports.PSObject.Properties[$rt.Id]) {
            $reportInfo = $repo.reports.($rt.Id)
        }
        if ($reportInfo -and $reportInfo.count -ge 0) {
            "<td><a href=`"$($repo.slug)/$($reportInfo.file)`">$($reportInfo.count) PRs</a></td>"
        } else {
            "<td class=`"na`">&mdash;</td>"
        }
    }
    "<tr><td class=`"report-name`">$($rt.Title)</td>$($cells -join '')</tr>"
}

# Build updated row with data-updated and data-interval attributes for JS
$updatedCells = $repos | ForEach-Object {
    $intervalH = if ($_.slug -eq "runtime") { 4 } else { 12 }
    "<td class=`"updated`" data-updated=`"$($_.updated)`" data-interval=`"$($intervalH)`">...</td>"
}
$updatedRow = "<tr class=`"updated-row`"><td class=`"report-name`">Updated</td>$($updatedCells -join '')</tr>"

# Build scan stats row — show analyzed count (scanned includes drafts/bots/stale that are filtered out)
$statsCells = $repos | ForEach-Object {
    $skipped = $_.scanned - $_.analyzed
    "<td class=`"stats`">$($_.analyzed) open PRs ($skipped drafts/bots excluded)</td>"
}
$statsRow = "<tr class=`"stats-row`"><td class=`"report-name`">Scan</td>$($statsCells -join '')</tr>"

$indexHtml = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PR Dashboard</title>
<style>
  :root { --bg: #0d1117; --fg: #e6edf3; --border: #30363d; --link: #58a6ff;
           --hover: #161b22; --header-bg: #161b22; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
         background: var(--bg); color: var(--fg); padding: 2em; }
  h1 { font-size: 1.6em; margin-bottom: 0.3em; }
  .meta { color: #8b949e; font-size: 0.85em; margin-bottom: 1.5em; }
  a { color: var(--link); text-decoration: none; }
  a:hover { text-decoration: underline; }
  table { border-collapse: collapse; margin-top: 1em; }
  th, td { padding: 8px 16px; border: 1px solid var(--border); text-align: center; }
  th { background: var(--header-bg); font-weight: 600; white-space: nowrap; }
  td.report-name { text-align: left; font-weight: 500; white-space: nowrap; }
  td.na { color: #484f58; }
  td.updated { color: #8b949e; font-size: 0.85em; }
  td.stats { color: #484f58; font-size: 0.8em; }
  tr.updated-row td, tr.stats-row td { border-top: 2px solid var(--border); }
  tr:hover { background: var(--hover); }
  .footer { margin-top: 2em; color: #8b949e; font-size: 0.85em; }
  @media (prefers-color-scheme: light) {
    :root { --bg: #fff; --fg: #1f2328; --border: #d0d7de; --link: #0969da;
             --hover: #f6f8fa; --header-bg: #f6f8fa; }
  }
</style>
</head>
<body>
<h1>PR Dashboard</h1>
<p class="meta">Automated PR triage reports for dotnet repositories</p>

<table>
<thead>
$headerRow
</thead>
<tbody>
$($dataRows -join "`n")
$updatedRow
$statsRow
</tbody>
</table>

<p class="footer">
  Generated by <a href="https://github.com/danmoseley/pr-dashboard">pr-dashboard</a> via GitHub Actions.
  Scoring by <a href="https://github.com/dotnet/runtime/pull/125005">pr-triage skill</a>.
</p>

<script>
function timeAgo(iso) {
  const ms = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(ms / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return mins + 'm ago';
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return hrs + 'h ago';
  const days = Math.floor(hrs / 24);
  return days + 'd ago';
}
function updateTimestamps() {
  document.querySelectorAll('[data-updated]').forEach(function(el) {
    var ago = timeAgo(el.getAttribute('data-updated'));
    var intervalH = el.getAttribute('data-interval');
    el.textContent = ago + ', updated every ' + intervalH + 'h';
  });
}
updateTimestamps();
setInterval(updateTimestamps, 60000);
</script>
</body>
</html>
"@

$indexHtml | Out-File -FilePath (Join-Path $DocsDir "index.html") -Encoding utf8
Write-Host "Generated index.html ($($repos.Count) repos)"
